kielas_rm_train:
  downloader:
    type: 'negative'
    background:
      url: "http://groups.csail.mit.edu/vision/LabelMe/NewImages/indoorCVPR_09.tar"
      tar_name: "indoorCVPR_09.tar"
      limit: 5000
      max_res: 1280
      min_res: 320
      use_proxy: false
      proxies:
        http: "http://127.0.0.1:7897"
        https: "http://127.0.0.1:7897"
      output_dir: './background'
    negative:
      url: "http://groups.csail.mit.edu/vision/LabelMe/NewImages/indoorCVPR_09.tar"
      tar_name: "indoorCVPR_09.tar"
      limit: 5000
      output_dir: "./negative"
      use_proxy: false
      proxies:
        http: "http://127.0.0.1:7897"
        https: "http://127.0.0.1:7897"
  
  negative_data:
    input_dir: './negative'
    output_dir: "~/autodl-fs/purify"

  sampler:
    max_num_classes: 13
    video_path: "D:\\Download\\negative.mp4"
    export_dir: "./data/purify"
    frame_step: 5  # 每隔多少帧抽取一次

  dataset:
    raw_dir: "./data/raw"      # 确保本地有这个目录
    purify_dir: "~/autodl-fs/purify" # "./data/purify"
    balance_dir: "./data/balance"
    datasets_dir: "./data/datasets"
    balance:
      max_samples_per_class: 3000

    augment:
      # --- 基础与光学增强 (适度放宽，避免特征完全损毁) ---
      brightness_prob: 0.8        
      brightness_range: [0.3, 3.0] # 【修改】回调过曝上限。3.0已足够模拟射灯，4.5会导致彻底白化
      blur_prob: 0.7              
      blur_ksize: [3, 5, 7, 9, 11]
      hsv_prob: 0.4              
      hsv_h_gain: 0.01           
      hsv_s_gain: 0.3             
      hsv_v_gain: 0.3             
      noise_prob: 0.7             
      bloom_prob: 0.2              # 【修改】降低光晕概率，过度泛光会严重干扰角点定位

      # --- 几何变换增强 (终极形变模式微调) ---
      flip_prob: 0.4              
      scale_prob: 0.6             
      roi_h_exp: 2.1
      roi_w_exp: 1.1
      scale_range: [0.01, 0.1]    
      rotate_prob: 0.6            
      rotate_range: [-45, 45]     
      translate_prob: 0.5         
      translate_range: 0.6        
      perspective_prob: 0.5       
      perspective_factor: 0.20     # 【修改】从 0.30 降至 0.20，防止四个角点交叉产生多边形自相交

      # --- 背景替换增强与遮挡 ---
      bg_replace_prob: 0.85       
      bg_dir: "./background"      
      occ_prob: 0.8               
      occ_radius_pct: 0.4         
      occ_size_pct: [0.02, 0.1]  

    split:
      val: 0.2

  # --- 训练超参数 ---
  train:
    device: "cuda"              # 可选: "auto", "cuda", "cpu"
    num_classes: 13
    negative_class_id: 12
    batch_size: 128
    prefetch_factor: 12         # 预取 批次 ，决定每次从硬盘读取多少数据
    epochs: 200
    weight_decay: 0.03          # 正则化惩罚力度 （0.01 - 0.05）
    save_dir: "./model_res"
    input_size: [416, 416]
    strides: [8, 16, 32]        # 缩放比例
    reg_max: 16                 # 关键点分布偏移网格范围参数

    continue:
      path: "./model_res/best_model.pth"

    shuffle_interval: 5         # 【保持】每 5 轮重新生成一次增强数据，打散数据分布
    optimizer:
      base_lr: 0.0003           # 【保持】稍低的基础学习率以稳定震荡
      betas: [0.940, 0.999] 
    
    scheduler:
      T_0: 100                  # 【保持】取消重启机制，直接退火至结束
      T_mult: 2
    
    post_process:
      conf_threshold: 0.5 
      kpt_dist_thresh: 15.0

    data:
      class_id: [0, 2, 5, 6, 8, 11, 12]
      train_img_dir: "./data/datasets/images/train"
      train_label_dir: "./data/datasets/labels/train"
      val_img_dir: "./data/datasets/images/val"
      val_label_dir: "./data/datasets/labels/val"
      num_workers: 16
      scale_ranges: [[0, 23], [20, 90], [87, 416]]

    # --- 损失函数权重 ---
    loss:
      lambda_pose: 5.0
      lambda_cls: 4.0   
      alpha: 0.25
      gamma: 2.0
      omega: 10.0
      epsilon: 2.0

    pck:
      target_in_range_dist: 10.0
      max_pixel_threshold: 5.0 
    
    # 综合评估得分权重配置
    metric_weights:
      pck: 0.65        # PCK 占总分的权重
      id_acc: 0.35     # 类别 ID 准确率占总分的权重

    early_stopping:
      enabled: false        
      min_score: 0.98        

kielas_rm_export:
  weights: "./model_res/best_model.pth"
  num_classes: 13                 
  negative_class_id: 12
  output_dir: "./export_res"
  formats: 
    - "onnx"
    - "torchscript"
  input_size: [416, 416]
  
  onnx:
    opset: 18
    simplify: true

kielas_rm_demo:
  camera_type: "hik" 
  camera_index: 0
  hik_exposure: 5000
  hik_gain: 10
  model_type: "onnx" 
  model_path: "./export_res/best_model.onnx"
  device: "cuda"
  num_classes: 13
  negative_class_id: 12                 
  input_size: [416, 416]
  strides: [8, 16, 32]
  conf_threshold: 0.7
  kpt_dist_thresh: 15.0