kielas_rm_train:
  # --- 训练超参数 ---
  train:
    device: "cuda"              # 可选: "auto", "cuda", "cpu"
    batch_size: 32
    epochs: 100
    weight_decay: 0.0005
    save_dir: "./model_res"
    input_size: [416, 416]
    grid_size: [52, 52]

    cache_loader:
      load: false
      device: 'cpu'
    
    learning_rate:
      base_lr: 0.001
      patience: 3
      factor: 0.5

    # 新增后处理配置块
    post_process:
      conf_threshold: 0.9
      nms_iou_threshold: 0.5

    data:
      # --- 数据集路径与加载配置 ---
      train_img_dir: "./data/datasets/images/train"
      train_label_dir: "./data/datasets/labels/train"
      val_img_dir: "./data/datasets/images/val"
      val_label_dir: "./data/datasets/labels/val"
      num_workers: 8

    # --- 损失函数权重 ---
    loss:
      lambda_conf: 1.0
      lambda_box: 1.5
      lambda_pose: 3.0
    # --- 新增：提前停止机制 ---
    early_stopping:
      enabled: true        # 是否开启自动停止
      min_val_loss: 0.05   # 验证集 loss 低于此值时触发停止

  dataset:
    balance:
      max_samples_per_class: 3000

    augment:
      # --- 基础与光学增强 ---
      brightness_prob: 0.3
      brightness_range: [0.9, 2.0]
      blur_prob: 0.2              # 运动模糊概率
      blur_ksize: [3, 5, 7]       # 模糊核大小选择
      hsv_prob: 0.3               # HSV色彩空间抖动概率
      hsv_h_gain: 0.015           # 色相变化幅度
      hsv_s_gain: 0.4             # 饱和度变化幅度
      hsv_v_gain: 0.8             # 明度变化幅度
      noise_prob: 0.2             # 高斯噪声概率
      bloom_prob: 0.4             # 光晕/过曝模拟概率
      
      # --- 几何变换增强 ---
      flip_prob: 0.15             # 水平翻转概率
      scale_prob: 0.3             # 缩放概率
      scale_range: [0.8, 1.2]
      rotate_prob: 0.2            # 旋转概率
      rotate_range: [-15, 15]
      translate_prob: 0.3         # 平移概率
      translate_range: 0.1        # 图像宽高比例的平移范围
      perspective_prob: 0.2       # 透视变换(形变)概率
      perspective_factor: 0.05    # 透视形变剧烈程度(0-0.2)

      # --- 背景替换增强 ---
      bg_replace_prob: 0.15        # 背景替换触发概率
      bg_dir: "./background"      # 背景图片存放文件夹
      bg_radius_factor: 1.5       # 约束圆半径倍数 (1.0 为刚好包围目标)
      
      # --- 遮挡增强 ---
      occ_prob: 0.2               # 随机遮挡概率
      occ_radius_pct: 0.15        # 遮挡中心偏离目标的半径比例

    split:
      val: 0.2

  tools:
    background:
      url: "http://groups.csail.mit.edu/vision/LabelMe/NewImages/indoorCVPR_09.tar"
      tar_name: "indoorCVPR_09.tar"
      limit: 5000
      max_res: 1280
      min_res: 320
      proxies:
        http: "http://127.0.0.1:7897"
        https: "http://127.0.0.1:7897"