kielas_rm_train:
  # --- 训练超参数 ---
  train:
    device: "cuda"              # 可选: "auto", "cuda", "cpu"
    batch_size: 32
    epochs: 300
    weight_decay: 0.0005
    save_dir: "./model_res"
    input_size: [416, 416]
    grid_size: [52, 52]

    continue:
      enabled: false
      path: "./model_res_tmp/best_model.pth"

    cache_loader:
      load: false
      device: 'cpu'
    
    optimizer:
      base_lr: 0.001
      betas: [0.940, 0.999] # 一阶矩估计的指数衰减率 将 0.9 改为 0.940

    # 新增后处理配置块
    post_process:
      # # 置信度阈值（通常是 conf_threshold = 0.5）。
      # 在前几个 epoch，模型还在“摸黑走路”，它输出的目标置信度可能只有 0.1 或者 0.2。
      # 既然连 0.5 的及格线都没到，NMS（非极大值抑制）阶段就把所有预测框全过滤掉了，相当于模型交了“白卷”，PCK 自然就是 0。
      conf_threshold: 0.8 
      nms_iou_threshold: 0.7

    data:
      class_id: [0, 2, 5, 6, 8, 11]
      # --- 数据集路径与加载配置 ---
      train_img_dir: "./data/datasets/images/train"
      train_label_dir: "./data/datasets/labels/train"
      val_img_dir: "./data/datasets/images/val"
      val_label_dir: "./data/datasets/labels/val"
      num_workers: 8

    # --- 损失函数权重 ---
    loss:
      lambda_conf: 1.0
      lambda_box: 1.5
      lambda_pose: 3.0
      lambda_cls: 2.0   # 新增分类损失的权重
      alpha: 0.85
      gamma: 2.0

    pck:
      target_in_range_dist: 20.0
      max_pixel_threshold: 5.0 # 根据网格计算比较适合的值，416x416 的图片大小对应 52x52 个网格，每个网格大小为 416/52 = 8，所以最好超过半个网格的大小，设定为 5
    
    # --- 新增：提前停止机制 ---
    early_stopping:
      enabled: true        # 是否开启自动停止
      min_pck: 0.98        # 验证集 pck 高于此值就停止训练

  dataset:
    balance:
      max_samples_per_class: 3000

    augment:
      # --- 基础与光学增强 ---
      brightness_prob: 0.3
      brightness_range: [0.9, 2.0]
      blur_prob: 0.2              # 运动模糊概率
      blur_ksize: [3, 5, 7]       # 模糊核大小选择
      hsv_prob: 0.3               # HSV色彩空间抖动概率
      hsv_h_gain: 0.015           # 色相变化幅度
      hsv_s_gain: 0.4             # 饱和度变化幅度
      hsv_v_gain: 0.8             # 明度变化幅度
      noise_prob: 0.2             # 高斯噪声概率
      bloom_prob: 0.4             # 光晕/过曝模拟概率
      
      # --- 几何变换增强 ---
      flip_prob: 0.15             # 水平翻转概率
      scale_prob: 0.3             # 缩放概率
      scale_range: [0.8, 1.2]
      rotate_prob: 0.2            # 旋转概率
      rotate_range: [-15, 15]
      translate_prob: 0.3         # 平移概率
      translate_range: 0.1        # 图像宽高比例的平移范围
      perspective_prob: 0.2       # 透视变换(形变)概率
      perspective_factor: 0.05    # 透视形变剧烈程度(0-0.2)

      # --- 背景替换增强 ---
      bg_replace_prob: 0.15        # 背景替换触发概率
      bg_dir: "./background"      # 背景图片存放文件夹
      bg_radius_factor: 1.5       # 约束圆半径倍数 (1.0 为刚好包围目标)
      
      # --- 遮挡增强 ---
      occ_prob: 0.2               # 随机遮挡概率
      occ_radius_pct: 0.15        # 遮挡中心偏离目标的半径比例

    split:
      val: 0.2

  tools:
    background:
      url: "http://groups.csail.mit.edu/vision/LabelMe/NewImages/indoorCVPR_09.tar"
      tar_name: "indoorCVPR_09.tar"
      limit: 5000
      max_res: 1280
      min_res: 320
      proxies:
        http: "http://127.0.0.1:7897"
        https: "http://127.0.0.1:7897"

kielas_rm_export:
  # 权重文件路径
  weights: "./model_res_300/best_model.pth"
  # 导出模型存放目录
  output_dir: "./export_res"
  # 导出格式列表，支持 "onnx", "torchscript"
  formats: 
    - "onnx"
    - "torchscript"
  # 模型输入尺寸 [宽, 高]
  input_size: [416, 416]
  
  onnx:
    opset: 18
    # 是否开启极致轻量化 (需要安装 onnx 和 onnx-simplifier)
    simplify: true

kielas_rm_demo:
  # 相机类型可选: "usb" (标准UVC相机), "hik" (海康工业相机)
  camera_type: "hik" 
  # 相机索引或视频文件路径
  camera_index: 0
  
  # 海康相机专用配置 (单位: us)
  hik_exposure: 5000
  hik_gain: 10
  
  # 原有配置保持不变...
  model_type: "onnx" 
  model_path: "./export_res/best_model.onnx"
  device: "cuda"
  input_size: [416, 416]
  grid_size: [52, 52]
  conf_threshold: 0.7
  nms_iou_threshold: 0.2